### ISSUE TITLE
Render width="" and height="" on <img> tag

### ISSUE THREAD

**Issue by Momkay** [ErikHen/PictureRenderer.Umbraco#1]
Is it possible to render the image width and height based on the picture profile size(s) on the `<img>` tag? Google PageSpeed checks this.

**Comment by ErikHen** [comment]
Thanks for the suggestion. I will investigate what is best practice for img element in a picture element. But I'm guessing Google is right 😉.

**Comment by ErikHen** [comment]
It's not clear to me what the best approach is. It's not a problem adding `height` and `width` attributes for the `<img>` element, since the aspect ratio is the same for all images. 
The `height` and `width` will give the browser a hint about the aspect ratio, and avoid CLS. But since `height` and `width` will be one of the values in `sizes` you need to set the actual size in css. And when you set the actual size/aspect in css, you will not have an issue with CLS, and the `height` and `width` are not needed(?).
Anyway, in version 1.3 it's possible to enable `ImgWidthHeight` in the Picture profile, and then `height` and `width` will be rendered.
